// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(filen_swiftFFI)
import filen_swiftFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_filen_swift_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_filen_swift_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureFilenSwiftInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol FilenClientProtocol: AnyObject, Sendable {
    
    func cancelAllDownloads()
    
    func cancelDownload(uuid: String)
    
    func cancellableDownloadFileToPath(fileUuid: String, path: String) async throws
    
    func createDirInDir(parentUuid: String, name: String) async throws  -> Directory
    
    func deleteDir(dirUuid: String) async throws
    
    func deleteFile(fileUuid: String) async throws
    
    func downloadFileToPath(fileUuid: String, path: String) async throws
    
    func exportCredentials()  -> Data
    
    func getDirInfo(dirUuid: String) async throws  -> Directory
    
    func getFileInfo(fileUuid: String) async throws  -> RemoteFile
    
    func listDir(dirUuid: String) async throws  -> ListDir
    
    func rootUuid()  -> String
    
    func uploadFileFromPath(dirUuid: String, filePath: String, fileName: String) async throws  -> RemoteFile
    
}
open class FilenClient: FilenClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_filen_swift_fn_clone_filenclient(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_filen_swift_fn_free_filenclient(pointer, $0) }
    }

    

    
open func cancelAllDownloads()  {try! rustCall() {
    uniffi_filen_swift_fn_method_filenclient_cancel_all_downloads(self.uniffiClonePointer(),$0
    )
}
}
    
open func cancelDownload(uuid: String)  {try! rustCall() {
    uniffi_filen_swift_fn_method_filenclient_cancel_download(self.uniffiClonePointer(),
        FfiConverterString.lower(uuid),$0
    )
}
}
    
open func cancellableDownloadFileToPath(fileUuid: String, path: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_cancellable_download_file_to_path(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(fileUuid),FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_void,
            completeFunc: ffi_filen_swift_rust_future_complete_void,
            freeFunc: ffi_filen_swift_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func createDirInDir(parentUuid: String, name: String)async throws  -> Directory  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_create_dir_in_dir(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(parentUuid),FfiConverterString.lower(name)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_rust_buffer,
            completeFunc: ffi_filen_swift_rust_future_complete_rust_buffer,
            freeFunc: ffi_filen_swift_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeDirectory_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func deleteDir(dirUuid: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_delete_dir(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dirUuid)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_void,
            completeFunc: ffi_filen_swift_rust_future_complete_void,
            freeFunc: ffi_filen_swift_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func deleteFile(fileUuid: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_delete_file(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(fileUuid)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_void,
            completeFunc: ffi_filen_swift_rust_future_complete_void,
            freeFunc: ffi_filen_swift_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func downloadFileToPath(fileUuid: String, path: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_download_file_to_path(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(fileUuid),FfiConverterString.lower(path)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_void,
            completeFunc: ffi_filen_swift_rust_future_complete_void,
            freeFunc: ffi_filen_swift_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func exportCredentials() -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
    uniffi_filen_swift_fn_method_filenclient_export_credentials(self.uniffiClonePointer(),$0
    )
})
}
    
open func getDirInfo(dirUuid: String)async throws  -> Directory  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_get_dir_info(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dirUuid)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_rust_buffer,
            completeFunc: ffi_filen_swift_rust_future_complete_rust_buffer,
            freeFunc: ffi_filen_swift_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeDirectory_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func getFileInfo(fileUuid: String)async throws  -> RemoteFile  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_get_file_info(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(fileUuid)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_rust_buffer,
            completeFunc: ffi_filen_swift_rust_future_complete_rust_buffer,
            freeFunc: ffi_filen_swift_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeRemoteFile_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func listDir(dirUuid: String)async throws  -> ListDir  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_list_dir(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dirUuid)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_rust_buffer,
            completeFunc: ffi_filen_swift_rust_future_complete_rust_buffer,
            freeFunc: ffi_filen_swift_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeListDir_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    
open func rootUuid() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_filen_swift_fn_method_filenclient_root_uuid(self.uniffiClonePointer(),$0
    )
})
}
    
open func uploadFileFromPath(dirUuid: String, filePath: String, fileName: String)async throws  -> RemoteFile  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_method_filenclient_upload_file_from_path(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(dirUuid),FfiConverterString.lower(filePath),FfiConverterString.lower(fileName)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_rust_buffer,
            completeFunc: ffi_filen_swift_rust_future_complete_rust_buffer,
            freeFunc: ffi_filen_swift_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeRemoteFile_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilenClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = FilenClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> FilenClient {
        return FilenClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: FilenClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FilenClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: FilenClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilenClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> FilenClient {
    return try FfiConverterTypeFilenClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilenClient_lower(_ value: FilenClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeFilenClient.lower(value)
}




public struct Directory {
    public var uuid: String
    public var name: String
    public var parentUuid: String
    public var favorited: Bool
    public var color: String?
    public var createdAt: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, name: String, parentUuid: String, favorited: Bool, color: String?, createdAt: UInt64?) {
        self.uuid = uuid
        self.name = name
        self.parentUuid = parentUuid
        self.favorited = favorited
        self.color = color
        self.createdAt = createdAt
    }
}

#if compiler(>=6)
extension Directory: Sendable {}
#endif


extension Directory: Equatable, Hashable {
    public static func ==(lhs: Directory, rhs: Directory) -> Bool {
        if lhs.uuid != rhs.uuid {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.parentUuid != rhs.parentUuid {
            return false
        }
        if lhs.favorited != rhs.favorited {
            return false
        }
        if lhs.color != rhs.color {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uuid)
        hasher.combine(name)
        hasher.combine(parentUuid)
        hasher.combine(favorited)
        hasher.combine(color)
        hasher.combine(createdAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDirectory: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Directory {
        return
            try Directory(
                uuid: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                parentUuid: FfiConverterString.read(from: &buf),
                favorited: FfiConverterBool.read(from: &buf),
                color: FfiConverterOptionString.read(from: &buf),
                createdAt: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: Directory, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.parentUuid, into: &buf)
        FfiConverterBool.write(value.favorited, into: &buf)
        FfiConverterOptionString.write(value.color, into: &buf)
        FfiConverterOptionUInt64.write(value.createdAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirectory_lift(_ buf: RustBuffer) throws -> Directory {
    return try FfiConverterTypeDirectory.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDirectory_lower(_ value: Directory) -> RustBuffer {
    return FfiConverterTypeDirectory.lower(value)
}


public struct ListDir {
    public var directories: [Directory]
    public var files: [RemoteFile]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(directories: [Directory], files: [RemoteFile]) {
        self.directories = directories
        self.files = files
    }
}

#if compiler(>=6)
extension ListDir: Sendable {}
#endif


extension ListDir: Equatable, Hashable {
    public static func ==(lhs: ListDir, rhs: ListDir) -> Bool {
        if lhs.directories != rhs.directories {
            return false
        }
        if lhs.files != rhs.files {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(directories)
        hasher.combine(files)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeListDir: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ListDir {
        return
            try ListDir(
                directories: FfiConverterSequenceTypeDirectory.read(from: &buf),
                files: FfiConverterSequenceTypeRemoteFile.read(from: &buf)
        )
    }

    public static func write(_ value: ListDir, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeDirectory.write(value.directories, into: &buf)
        FfiConverterSequenceTypeRemoteFile.write(value.files, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListDir_lift(_ buf: RustBuffer) throws -> ListDir {
    return try FfiConverterTypeListDir.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeListDir_lower(_ value: ListDir) -> RustBuffer {
    return FfiConverterTypeListDir.lower(value)
}


public struct RemoteFile {
    public var uuid: String
    public var name: String
    public var mime: String
    public var lastModified: UInt64
    public var created: UInt64
    public var parent: String
    public var size: UInt64
    public var favorited: Bool
    public var region: String
    public var bucket: String
    public var chunks: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(uuid: String, name: String, mime: String, lastModified: UInt64, created: UInt64, parent: String, size: UInt64, favorited: Bool, region: String, bucket: String, chunks: UInt64) {
        self.uuid = uuid
        self.name = name
        self.mime = mime
        self.lastModified = lastModified
        self.created = created
        self.parent = parent
        self.size = size
        self.favorited = favorited
        self.region = region
        self.bucket = bucket
        self.chunks = chunks
    }
}

#if compiler(>=6)
extension RemoteFile: Sendable {}
#endif


extension RemoteFile: Equatable, Hashable {
    public static func ==(lhs: RemoteFile, rhs: RemoteFile) -> Bool {
        if lhs.uuid != rhs.uuid {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.mime != rhs.mime {
            return false
        }
        if lhs.lastModified != rhs.lastModified {
            return false
        }
        if lhs.created != rhs.created {
            return false
        }
        if lhs.parent != rhs.parent {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.favorited != rhs.favorited {
            return false
        }
        if lhs.region != rhs.region {
            return false
        }
        if lhs.bucket != rhs.bucket {
            return false
        }
        if lhs.chunks != rhs.chunks {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(uuid)
        hasher.combine(name)
        hasher.combine(mime)
        hasher.combine(lastModified)
        hasher.combine(created)
        hasher.combine(parent)
        hasher.combine(size)
        hasher.combine(favorited)
        hasher.combine(region)
        hasher.combine(bucket)
        hasher.combine(chunks)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRemoteFile: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RemoteFile {
        return
            try RemoteFile(
                uuid: FfiConverterString.read(from: &buf),
                name: FfiConverterString.read(from: &buf),
                mime: FfiConverterString.read(from: &buf),
                lastModified: FfiConverterUInt64.read(from: &buf),
                created: FfiConverterUInt64.read(from: &buf),
                parent: FfiConverterString.read(from: &buf),
                size: FfiConverterUInt64.read(from: &buf),
                favorited: FfiConverterBool.read(from: &buf),
                region: FfiConverterString.read(from: &buf),
                bucket: FfiConverterString.read(from: &buf),
                chunks: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: RemoteFile, into buf: inout [UInt8]) {
        FfiConverterString.write(value.uuid, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.mime, into: &buf)
        FfiConverterUInt64.write(value.lastModified, into: &buf)
        FfiConverterUInt64.write(value.created, into: &buf)
        FfiConverterString.write(value.parent, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterBool.write(value.favorited, into: &buf)
        FfiConverterString.write(value.region, into: &buf)
        FfiConverterString.write(value.bucket, into: &buf)
        FfiConverterUInt64.write(value.chunks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteFile_lift(_ buf: RustBuffer) throws -> RemoteFile {
    return try FfiConverterTypeRemoteFile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemoteFile_lower(_ value: RemoteFile) -> RustBuffer {
    return FfiConverterTypeRemoteFile.lower(value)
}


public enum FilenClientError: Swift.Error {

    
    
    case ConcurrencyError(msg: String
    )
    case FilenClientError(msg: String
    )
    case TypeConversionError(msg: String
    )
    case IoError(msg: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFilenClientError: FfiConverterRustBuffer {
    typealias SwiftType = FilenClientError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FilenClientError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ConcurrencyError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 2: return .FilenClientError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 3: return .TypeConversionError(
            msg: try FfiConverterString.read(from: &buf)
            )
        case 4: return .IoError(
            msg: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FilenClientError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ConcurrencyError(msg):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .FilenClientError(msg):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .TypeConversionError(msg):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(msg, into: &buf)
            
        
        case let .IoError(msg):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msg, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilenClientError_lift(_ buf: RustBuffer) throws -> FilenClientError {
    return try FfiConverterTypeFilenClientError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFilenClientError_lower(_ value: FilenClientError) -> RustBuffer {
    return FfiConverterTypeFilenClientError.lower(value)
}


extension FilenClientError: Equatable, Hashable {}




extension FilenClientError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeDirectory: FfiConverterRustBuffer {
    typealias SwiftType = [Directory]

    public static func write(_ value: [Directory], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeDirectory.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Directory] {
        let len: Int32 = try readInt(&buf)
        var seq = [Directory]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeDirectory.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRemoteFile: FfiConverterRustBuffer {
    typealias SwiftType = [RemoteFile]

    public static func write(_ value: [RemoteFile], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRemoteFile.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RemoteFile] {
        let len: Int32 = try readInt(&buf)
        var seq = [RemoteFile]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRemoteFile.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureFilenSwiftInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
public func clientFromCredentials(clientCredentials: Data)throws  -> FilenClient  {
    return try  FfiConverterTypeFilenClient_lift(try rustCallWithError(FfiConverterTypeFilenClientError_lift) {
    uniffi_filen_swift_fn_func_client_from_credentials(
        FfiConverterData.lower(clientCredentials),$0
    )
})
}
public func login(email: String, pwd: String, twoFactorCode: String)async throws  -> FilenClient  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_filen_swift_fn_func_login(FfiConverterString.lower(email),FfiConverterString.lower(pwd),FfiConverterString.lower(twoFactorCode)
                )
            },
            pollFunc: ffi_filen_swift_rust_future_poll_pointer,
            completeFunc: ffi_filen_swift_rust_future_complete_pointer,
            freeFunc: ffi_filen_swift_rust_future_free_pointer,
            liftFunc: FfiConverterTypeFilenClient_lift,
            errorHandler: FfiConverterTypeFilenClientError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_filen_swift_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_filen_swift_checksum_func_client_from_credentials() != 18420) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_func_login() != 49467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_cancel_all_downloads() != 62888) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_cancel_download() != 23438) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_cancellable_download_file_to_path() != 1583) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_create_dir_in_dir() != 914) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_delete_dir() != 25040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_delete_file() != 8975) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_download_file_to_path() != 47710) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_export_credentials() != 37485) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_get_dir_info() != 26955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_get_file_info() != 14617) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_list_dir() != 33482) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_root_uuid() != 61878) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_filen_swift_checksum_method_filenclient_upload_file_from_path() != 36275) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureFilenSwiftInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all
